### ISSUE TITLE
Installation Instructions should include Rake Migrate

### ISSUE THREAD

**Issue by cparis** [fathomssen/redmine_edit_custom_fields#1]
Need to add this to the installation instructions to add additional database column:

rake redmine:plugins:migrate NAME=redmine_edit_custom_fields RAILS_ENV=production

**Comment by fathomssen** [comment]
Thanks, done!

**Comment by fathomssen** [comment]
Btw: If the plugin works for you, please feel free to rate it on the [Redmine plugin page](https://www.redmine.org/plugins/redmine_edit_custom_fields)
