### ISSUE TITLE
[doc] simple explanation of which users can edit

### ISSUE THREAD

**Issue by antoinetran** [fathomssen/redmine_edit_custom_fields#16]
Hi,

I looked at this great plugin because our projects needs to let some manager change fields without being admin. However I do not see or understand which users are allowed to edit custom fields? Do we have a dedicated new role? I just want to be sure that no the average user can edit the fields. I suppose the answer is yes but just to be sure, thanks!

**Comment by fathomssen** [comment]
Hi @antoinetran 

As described in the [configuration section](https://github.com/fathomssen/redmine_edit_custom_fields#configuration), you can authorise an existing or a new user role to be able to editor custom fields. This user role would be able to edit _any_ custom fields though.

Cheers
Freddy
