### ISSUE TITLE
don't work on 3.2.1

### ISSUE THREAD

**Issue by tnkhide** [fathomssen/redmine_edit_custom_fields#3]
Hello,I'm using Bitnami Redmine 3.2.1 on Windows7.
Installation worked fine,but plugin don't work.
Do you have any idea?

`Environment:`
`Redmine version                3.2.1.stable`
`Ruby version                   2.1.7-p400 (2015-08-18) [i386-mingw32]`
`Rails version                  4.2.5.2`
`Environment                    production`
`Database adapter               Mysql2`

`C:\Bitnami\redmine-3.2.1-0\apps\redmine\htdocs>bundle exec rake redmine:plugins:migrate NAME=redmine_edit_custom_fields RAILS_ENV=pr
oduction`
`DL is deprecated, please use Fiddle`
`Migrating redmine_edit_custom_fields (Redmine Edit Custom Fields plugin)...`
`== 1 AddUserEditableToCustomField: migrating ==================================
-- add_column(:custom_fields, :user_editable, :boolean, {:default=>false, :null=>false})`
`-> 0.4836s`
`== 1 AddUserEditableToCustomField: migrated (0.4836s) =========================`

![screen](https://cloud.githubusercontent.com/assets/11384055/14038739/24c98bbe-f298-11e5-911d-2498ece9455a.png)
[production.zip](https://github.com/fathomssen/redmine_edit_custom_fields/files/189111/production.zip)

**Comment by fathomssen** [comment]
Hi @tnkhide 

My configuration instruction is obviously missing a crucial point: You have to enable the user-editing for each custom field that should be user-editable. I will update the instructions asap.

Best regards
Frederick Thomssen

**Comment by fathomssen** [comment]
Please have a look at the lastest readme file: https://github.com/fathomssen/redmine_edit_custom_fields/blob/master/README.md

**Comment by tnkhide** [comment]
Hi, Thanks. It’s OK now.
