### ISSUE TITLE
Values changed everywhere after changing them in one project

### ISSUE THREAD

**Issue by ghost** [fathomssen/redmine_edit_custom_fields#6]
Hello,
I tried the plugin but I have a question whether is it possible to have the custom field values completely specific to a certain project.
I tried changing the values in project A, and then they were also shown in project B. Could this somehow be changed?

**Comment by fathomssen** [comment]
Hi

I am sorry - due to the design of Redmine, this is not possible. What I usually do is to create a custom field for each project (e.g. "P1 Custom Field 1" and "P2 Custom Field 1"). You can set the values for each custom field then.

Best regards
Frederick Thomssen
