### ISSUE TITLE
Cannot install on redmine 3.2.1

### ISSUE THREAD

**Issue by andrewsze** [fathomssen/redmine_edit_custom_fields#7]
I cannot install on redmine 3.2.1 succesfully. Please help. Below are the environment info. and the installation log. Please advise if further info. is needed.

Environment:
  Redmine version                3.2.1.stable
  Ruby version                   2.3.1-p112 (2016-04-26) [x86_64-linux-gnu]
  Rails version                  4.2.6
  Environment                    production
  Database adapter               PostgreSQL
SCM:
  Git                            2.7.4
  Filesystem                     
Redmine plugins:
  no plugin installed

Intallation log:

rake redmine:plugins:migrate NAME=redmine_edit_custom_fields RAILS_ENV=production --trace
(in /usr/share/redmine)
** Invoke redmine:plugins:migrate (first_time)
** Invoke environment (first_time)
** Execute environment
rake aborted!
NameError: uninitialized constant EditCustomFieldsHelper
/usr/share/redmine/lib/plugins/redmine_edit_custom_fields/init.rb:43:in `block (2 levels) in <top (required)>'
/usr/lib/ruby/vendor_ruby/active_support/callbacks.rb:446:in `instance_exec'
/usr/lib/ruby/vendor_ruby/active_support/callbacks.rb:446:in `block in make_lambda'
/usr/lib/ruby/vendor_ruby/active_support/callbacks.rb:192:in `block in simple'
/usr/lib/ruby/vendor_ruby/active_support/callbacks.rb:504:in `block in call'
/usr/lib/ruby/vendor_ruby/active_support/callbacks.rb:504:in `each'
/usr/lib/ruby/vendor_ruby/active_support/callbacks.rb:504:in `call'
/usr/lib/ruby/vendor_ruby/active_support/callbacks.rb:92:in `__run_callbacks__'
/usr/lib/ruby/vendor_ruby/active_support/callbacks.rb:778:in `_run_prepare_callbacks'
/usr/lib/ruby/vendor_ruby/active_support/callbacks.rb:81:in `run_callbacks'
/usr/lib/ruby/vendor_ruby/action_dispatch/middleware/reloader.rb:83:in `prepare!'
/usr/lib/ruby/vendor_ruby/action_dispatch/middleware/reloader.rb:55:in `prepare!'
/usr/lib/ruby/vendor_ruby/rails/application/finisher.rb:50:in `block in <module:Finisher>'
/usr/lib/ruby/vendor_ruby/rails/initializable.rb:30:in `instance_exec'
/usr/lib/ruby/vendor_ruby/rails/initializable.rb:30:in `run'
/usr/lib/ruby/vendor_ruby/rails/initializable.rb:55:in `block in run_initializers'
/usr/lib/ruby/2.3.0/tsort.rb:228:in `block in tsort_each'
/usr/lib/ruby/2.3.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
/usr/lib/ruby/2.3.0/tsort.rb:431:in `each_strongly_connected_component_from'
/usr/lib/ruby/2.3.0/tsort.rb:349:in `block in each_strongly_connected_component'
/usr/lib/ruby/2.3.0/tsort.rb:347:in `each'
/usr/lib/ruby/2.3.0/tsort.rb:347:in `call'
/usr/lib/ruby/2.3.0/tsort.rb:347:in `each_strongly_connected_component'
/usr/lib/ruby/2.3.0/tsort.rb:226:in `tsort_each'
/usr/lib/ruby/2.3.0/tsort.rb:205:in `tsort_each'
/usr/lib/ruby/vendor_ruby/rails/initializable.rb:54:in `run_initializers'
/usr/lib/ruby/vendor_ruby/rails/application.rb:352:in `initialize!'
/usr/share/redmine/config/environment.rb:14:in `<top (required)>'
/usr/lib/ruby/vendor_ruby/rails/application.rb:328:in `require_environment!'
/usr/lib/ruby/vendor_ruby/rails/application.rb:457:in `block in run_tasks_blocks'
/var/lib/gems/2.3.0/gems/rake-11.3.0/lib/rake/task.rb:248:in `block in execute'
/var/lib/gems/2.3.0/gems/rake-11.3.0/lib/rake/task.rb:243:in `each'
/var/lib/gems/2.3.0/gems/rake-11.3.0/lib/rake/task.rb:243:in `execute'
/var/lib/gems/2.3.0/gems/rake-11.3.0/lib/rake/task.rb:187:in `block in invoke_with_call_chain'
/usr/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/var/lib/gems/2.3.0/gems/rake-11.3.0/lib/rake/task.rb:180:in `invoke_with_call_chain'
/var/lib/gems/2.3.0/gems/rake-11.3.0/lib/rake/task.rb:209:in `block in invoke_prerequisites'
/var/lib/gems/2.3.0/gems/rake-11.3.0/lib/rake/task.rb:207:in `each'
/var/lib/gems/2.3.0/gems/rake-11.3.0/lib/rake/task.rb:207:in `invoke_prerequisites'
/var/lib/gems/2.3.0/gems/rake-11.3.0/lib/rake/task.rb:186:in `block in invoke_with_call_chain'
/usr/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/var/lib/gems/2.3.0/gems/rake-11.3.0/lib/rake/task.rb:180:in `invoke_with_call_chain'
/var/lib/gems/2.3.0/gems/rake-11.3.0/lib/rake/task.rb:173:in `invoke'
/var/lib/gems/2.3.0/gems/rake-11.3.0/lib/rake/application.rb:152:in `invoke_task'
/var/lib/gems/2.3.0/gems/rake-11.3.0/lib/rake/application.rb:108:in `block (2 levels) in top_level'
/var/lib/gems/2.3.0/gems/rake-11.3.0/lib/rake/application.rb:108:in `each'
/var/lib/gems/2.3.0/gems/rake-11.3.0/lib/rake/application.rb:108:in `block in top_level'
/var/lib/gems/2.3.0/gems/rake-11.3.0/lib/rake/application.rb:117:in `run_with_threads'
/var/lib/gems/2.3.0/gems/rake-11.3.0/lib/rake/application.rb:102:in `top_level'
/var/lib/gems/2.3.0/gems/rake-11.3.0/lib/rake/application.rb:80:in `block in run'
/var/lib/gems/2.3.0/gems/rake-11.3.0/lib/rake/application.rb:178:in `standard_exception_handling'
/var/lib/gems/2.3.0/gems/rake-11.3.0/lib/rake/application.rb:77:in `run'
/var/lib/gems/2.3.0/gems/rake-11.3.0/exe/rake:27:in `<top (required)>'
/usr/local/bin/rake:23:in `load'
/usr/local/bin/rake:23:in `<main>'
Tasks: TOP => redmine:plugins:migrate => environment

**Comment by fathomssen** [comment]
Hi @andrewsze 

I just wonder: Why is your plugin directory in `/usr/share/redmine/lib/plugins` and not in `/usr/share/redmine/plugins` (mind the `lib`)? I know that Ruby on Rails or Redmine sometimes behave strange when you do not install the plugins to the "correct" directory.

On the other hand, this might be a Ruby version issue. I will look into it anyway.

Best regards
Frederick Thomssen

**Comment by andrewsze** [comment]
Hi Frederick,

After modifying the plugins directory location, the plugin can be installed properly. Thank you for your help.

Andrew

**Comment by fathomssen** [comment]
Hi Andrew

You're welcome. I will update the readme file to make more clear that you have to use exactly the specified folders.

Best regards
Frederick Thomssen

**Comment by fathomssen** [comment]
Fixed with commit 0c07bc05f05d61d63dd0e5e0aa5df4c92e8cd514
