### ISSUE TITLE
Redmine 3.4.2 not able to save "user_editable"

### ISSUE THREAD

**Issue by pixelworksIT** [fathomssen/redmine_edit_custom_fields#9]
I am using 0.0.4 with Redmine 3.4.2 . In "Administration" -> "Custom fields", when editing a custom field, check "User editable" and "Save", but it will not save "User editable". So after page reloaded, "User editable" still remain unchecked, while the message said it's saved successfully.

**Comment by fathomssen** [comment]
Hi @pwitpubrepo 

Have you performed the migration?

`
rake redmine:plugins:migrate NAME=redmine_edit_custom_fields RAILS_ENV=production
`

Best regards
Frederick Thomssen

**Comment by pixelworksIT** [comment]
Yes, I did. I was following the official steps to install the plugins.

**Comment by fathomssen** [comment]
OK, could you please provide me with the appropriate sections of your `log/production.log` file?

**Comment by pixelworksIT** [comment]
Hi, Frederick, please see following log

Started PUT "/custom_fields/4" for 10.0.0.1 at 2017-07-26 08:09:21 +0000
Processing by CustomFieldsController#update as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"Oh277aRhenpVH8uSIeMWegiwSECr2830hNX6jIGYr4ufHbCtJdeJdVW1chIb/emz9C4FL1tQXWpcdl7GwtjDnA==", "custom_field"=>{"name"=>"sw ver.", "description"=>"Issue for specific software version", "multiple"=>"1", "possible_values"=>"0.1a\r\n0.1b\r\n0.1", "default_value"=>"", "url_pattern"=>"", "edit_tag_style"=>"", "is_required"=>"1", "is_filter"=>"1", "searchable"=>"1", "user_editable"=>"1", "visible"=>"1", "role_ids"=>[""], "tracker_ids"=>["1", "2", "3", ""], "is_for_all"=>"0", "project_ids"=>["8", "4", ""]}, "commit"=>"Save", "id"=>"4"}
  Current user: hyli (id=5)
Redirected to http://redmine.test.pixelworks.com/custom_fields/4/edit
Completed 302 Found in 47ms (ActiveRecord: 15.7ms)
Started GET "/custom_fields/4/edit" for 10.0.0.1 at 2017-07-26 08:09:21 +0000
Processing by CustomFieldsController#edit as HTML
  Parameters: {"id"=>"4"}
  Current user: hyli (id=5)
  Rendered custom_fields/formats/_list.html.erb (2.8ms)
  Rendered plugins/redmine_edit_custom_fields/app/views/custom_fields/_options.html.erb (0.3ms)
  Rendered custom_fields/_form.html.erb (25.7ms)
  Rendered custom_fields/edit.html.erb within layouts/admin (27.4ms)
  Rendered admin/_menu.html.erb (6.2ms)
  Rendered layouts/base.html.erb (20.9ms)
Completed 200 OK in 65ms (Views: 51.6ms | ActiveRecord: 6.7ms)

**Comment by fathomssen** [comment]
Hmm, no error message at all. Could you please

1. post the production.log from the time of the plugin installation and migration?
2. Look up whether the database field custom_fields.user_editable exists?

Best regards
Frederick Thomssen

**Comment by fathomssen** [comment]
OK, I can reproduce the problem with Redmine 3.4.2. I will look into this. Thanks for reporting the problem!

**Comment by fathomssen** [comment]
Hi @pwitpubrepo  

Redmine chose to silently introduce `safe_attributes` for custom fields, breaking this plugin.

Fixed it in version 0.0.5: https://github.com/fathomssen/redmine_edit_custom_fields/releases/tag/v0.0.5

Best regards
Frederick Thomssen

**Comment by pixelworksIT** [comment]
Thank you, Sir. I was still strugling to get some error messages from the log, But there isn't any :) Now Thank you for the fix. That helps a lot
在 2017年7月29日 上午2:46，Frederick Thomssen <notifications@github.com>写道：<br type="attributi

Hi @pwitpubrepo<https://github.com/pwitpubrepo>

Redmine chose to silently introduce safe_attributes for custom fields, breaking this plugin.

Fixed it in version 0.0.5: https://github.com/fathomssen/redmine_edit_custom_fields/releases/tag/v0.0.5

Best regards
Frederick Thomssen

―
